### ISSUE TITLE
execute-batch does not support {:return-keys true}

### ISSUE THREAD

**Issue by guv** [seancorfield/next-jdbc#109]
When doing a batch insert via `execute-batch`, the `:return-keys true` in the options map has no effect.
Is it possible to support that as well?
Is there an alternative approach to use batches to insert a larger number of rows?

**Comment by seancorfield** [comment]
`execute-batch!` takes a `PreparedStatement`. `:return-keys true` applies to the creation of the prepared statement, not to the execution. In addition `.executeBatch()` (in `java.sql.Statement`) returns update counts. And since `execute-batch!` is documented to return update counts, that's what you get.

That said, if you want the generated keys back, you can do it yourself (for _most_ databases -- MS SQL Server does not allow this):
```clojure
(with-open [ps (jdbc/prepare ds ["... SQL ..." arg1 arg2] {:return-keys true})]
  ;; returns update counts:
  (p/execute-batch! ps ...)
  ;; produce generated keys as Clojure data:
  (rs/datafiable-result-set (.getGeneratedKeys ps) ds {}))
```
I'll add an example of this in the docs.

**Comment by guv** [comment]
Thank you for your quick feedback. That is definitely a good addition to the docs for Clojure devs with limited exposure to the JDBC details. :+1:

**Comment by seancorfield** [comment]
`next.jdbc` does assume/require a bit more knowledge of JDBC because it's "closer to the metal" than `clojure.java.jdbc` was (and it's faster because of that difference) but since I've been working with these libs for years now I'm not always spotting where I'm assuming JDBC familiarity -- so thank you for catching this and helping me improve the docs! Much appreciated.
