### ISSUE TITLE
Provide access to column names via plan

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/next-jdbc#110]
**Is your feature request related to a problem? Please describe.**
If you use array builders with `plan`, you do not get the column names as the first "row", you get the actual first row of the data. That makes it hard to do anything that requires knowing which columns in the row match which name (label).

**Describe the solution you'd like**
Inside the reducing function, you have a mapified result set (row), and you should be able to access at least the columns from inside the builder (and preferably all three parts: the result set, the result set metadata, and the column names).

**Comment by geraldodev** [comment]
What I was doing was
```
(transduce
        (comp
          (map #(into [] %)) ;; force vector realization
          (map-indexed idx-v-fn)
          (partition-all 100))
        (completing
          (fn [_ lote]
            (doseq [[idx v] lote]
              (let [row (.createRow sh idx)]
                (doseq [[idx-cell vr-campo]  (map-indexed idx-v-fn v)]
                  (let [cell (.createCell row idx-cell)]
                    (try
                      (set-cell-value cell vr-campo)
                      (catch Exception e
                        (println "Deu errado pro tipo " (type vr-campo))
                        (throw e)))))))))
        []
        (jdbc/plan conn sql {:builder-fn rs/as-arrays}))
```
For this case the behaviour of jdbc/execute! of returning the names before the first row is enough.
It would be nice if we had a map of field index to the name of the field, because this information is hard to capture inside a transducer, that is not the case of jdbc/execute! because it materializes the entire result and the names are acessible via (nth 0).

A curiosity, I'm using oracle and at the begining of my issue I was blaming the Oracle because in the message there was a getMetadata, but It was about the row not being realized and a closed statement being accessed.  After that I've inserted at the start
```
  (map #(into [] %))
```
to force the vector realization.

If you ask me I'd make the realization of the the map as-map or the array default, and would provide a flag to turn it off to get the extra performance bit, because errors like this are difficult to catch.

**Comment by seancorfield** [comment]
`plan` was designed to be used with hash map semantics on the rows -- you'll see it calls `mapify-result-set` -- so there's always been a strong assumption that you'd be using a map-based builder. I don't think I've even tested it with an array-based builder, but that's why you have to essentially call `seq` (via `into`) to get a realized sequence. That, in turn, invokes the `row-builder` which reduces over the column indices to build a row of data (a vector).

In this particular case, you're essentially duplicating work because you end up with the equivalent of:
```clojure
(into [] (seq (reduce conj [] column-data)))
```
so I can make that faster as well.

And, no, at this point the default behavior _must_ be the fast path here: adding an option would "break" existing code that depends on the fast path and it would also slow that path down by needing to check the option.

`execute!` is the simple (slower) path that avoid the complexities of realization. The "option" that gets you the "performance bit" is using `plan` in the first place :)

**Comment by seancorfield** [comment]
p.s. I believe you could just `(map #(rs/datafiable-row % conn {}))` instead of `(map #(into [] %))` and that will avoid the duplicate work I mentioned above.

**Comment by seancorfield** [comment]
@geraldodev Here's a test that's a simplified version of what you're doing: https://github.com/seancorfield/next-jdbc/blob/master/test/next/jdbc/result_set_test.clj#L239-L252

**Comment by geraldodev** [comment]
Thank you very much
