### ISSUE TITLE
Boolean values into SQLite get stored by SQLite as 0/1 and queried back through next.jdbc as Clojure numbers.

### ISSUE THREAD

**Issue by eihli** [seancorfield/next-jdbc#134]
**To Reproduce**

```clojure
  (require '[next.jdbc :as jdbc])

  (def db-spec {:dbtype "sqlite" :dbname "example-db"})

  (jdbc/execute!
   db-spec
   ["create table if not exists users (name text, is_active bool)"])

  (jdbc/execute!
   db-spec
   ["insert into users (name, is_active) values (?, ?)" "alice" true])

  (jdbc/execute!
   db-spec
   ["select * from users"])
  ;; => [#:users{:name "alice", :is_active 1}]
```

I'd expect `is_active` on that last line to be `true`, not `1`.

SQLite doesn't have a "bool" data type. Instead, it matches on text in the declared type and uses affinity of either INTEGER, TEXT, BLOB, REAL, or NUMERIC.

https://www.sqlite.org/datatype3.html
```
3.1. Determination Of Column Affinity
The affinity of a column is determined by the declared type of the column, according to the following rules in the order shown:
    If the declared type contains the string "INT" then it is assigned INTEGER affinity.
    If the declared type of the column contains any of the strings "CHAR", "CLOB", or "TEXT" then that column has TEXT affinity. Notice that the type VARCHAR contains the string "CHAR" and is thus assigned TEXT affinity.
    If the declared type for a column contains the string "BLOB" or if no type is specified then the column has affinity BLOB.
    If the declared type for a column contains any of the strings "REAL", "FLOA", or "DOUB" then the column has REAL affinity.
    Otherwise, the affinity is NUMERIC.
```

I can see an argument that it's not the responsibility of `next.jdbc`. It would surely be a breaking change for any applications that have coded around this.

The `org.xerial/sqlite-jdbc` driver doesn't consider anything other than the SQLite affinities.
https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java#L610

"... **Otherwise, the affinity is NUMERIC**"

That last bit is interesting. It means `create table users (id INT, is_active BOOLEAN)` is the same as `create table users (id INT, is_active BOOL)` is the same as `create table users (id INT, is_active FOOBAR)` and there's not technically an SQLite-standard way of defining boolean columns which means there is no standardized way of detecting them. We'd be stuck relying on convention.

Something like the following might be close to an answer.

```clojure
(extend-protocol result-set/ReadableColumn
  Integer
  (read-column-by-index [x mrs i]
    (if (re-find #"(?i)bool" (.getColumnTypeName mrs i))
      (if (= 1 x) true false)
      x)))
```

**Comment by seancorfield** [comment]
I'm adding tests around this now and here are my findings so far:
* Most databases support `bool` as a column type (although some only accept `boolean`) but MS SQL Server does not: it requires `bit`.
* All databases seem to _store_ `bool` (or `bit`) as `0` or `1` under the hood as far as I can tell but...
* ...all databases _except_ SQLite will return `bool` (and `bit`) as `false` or `true` -- only SQLite insists on returning that column type as `0` or `1`

Here's the full list of types my testing databases support (testing `bool` first, then `boolean`, then `bit`):
```
derby supports BOOLEAN (but not BIT)
h2:mem supports BOOL
h2 supports BOOL
hsqldb supports BOOLEAN
sqlite supports BOOL
embedded-postgres supports BOOL
mysql supports BOOL
mssql supports BIT
jtds supports BIT
```

**Comment by seancorfield** [comment]
SQLite is the odd one out here so there's really nothing I can do that would solve SQLite's "problem" in a zero-overhead manner (extending `ReadableColumn` would introduce a performance penalty for _everyone_ so that's not an option).

For your specific case, you could use either extend the protocol (as above, with the caveat that it would break `plan` I think) or use `next.jdbc.result-set/builder-adapter` to wrap an existing builder and then provide a column reader that checks the metadata and calls either `.getObject` or `.getBoolean` which I think would be cleaner.

Neither of those will solve your problem for `plan` (just for `execute!` / `execute-one!` and the friendly SQL functions), since it really only has the column label to work from but you do have access to the `ResultSetMetaData` (via the `metadata` function) and you could figure out the column index based on the column label and use that to look up the column type -- `plan` is intended to be fast by avoiding the result set realization as a data structure which is why it sidesteps that data normally. Of course, if you know the column label and the query you're working with you can always just convert the `0` / `1` value to a Boolean with `pos?`: `(pos? (:is_active row))` inside `plan`'s reducing function.

**Comment by seancorfield** [comment]
I added a new **SQLite** section to the **Tips & Tricks** page that shows a `builder-adapter` that will work (and there's a specific test using it too):
* https://github.com/seancorfield/next-jdbc/blob/develop/doc/tips-and-tricks.md#sqlite
* https://github.com/seancorfield/next-jdbc/blob/develop/test/next/jdbc_test.clj#L341

**Comment by seancorfield** [comment]
And here's the `plan` workaround as a test, based on the **Tips & Tricks** suggestion:
* https://github.com/seancorfield/next-jdbc/blob/develop/test/next/jdbc_test.clj#L359

**Comment by eihli** [comment]
Thanks. You do great work. This might be obvious to anyone who gets to that SQLite help doc, but `"BOOLEAN"` could also be in to that `{"BIT" "BOOL"}` set. I mention it since that's how I wrote my schema.

**Comment by seancorfield** [comment]
Updated **Tips & Tricks** to add `"BOOLEAN"` as well.
