### ISSUE TITLE
How to supply multiple parameters

### ISSUE THREAD

**Issue by Ayush1325** [seancorfield/next-jdbc#147]
Ok, so I was just wondering how can I supply multiple parameters in `execute!` and `execute-one!` since I couldn't find any example of doing that in the docs other than using prepared statements. I have tried doing the following:
```clojure
(jdbc/execute-one! common-db/ds
                            ["UPDATE reports
                            set test_data = jsonb_set_lax(test_data, '( ? }', ?, true, 'delete_key')
                            WHERE id = ?" "coo" {} #uuid"815984ae-21b8-4edb-88e7-0b307cd9c357"]
                            (merge jdbc/unqualified-snake-kebab-opts
                                   {:timeout 5}))
```
And also tried this as it was present in golang
```clojure
(jdbc/execute-one! common-db/ds
                            ["UPDATE reports
                            set test_data = jsonb_set_lax(test_data, '( $1 }', $2, true, 'delete_key')
                            WHERE id = $3" "coo" {} #uuid"815984ae-21b8-4edb-88e7-0b307cd9c357"]
                            (merge jdbc/unqualified-snake-kebab-opts
                                   {:timeout 5}))
```
But both of the above don't work. I can kinda hack it by constructing query using `format`:
```clojure
(jdbc/execute-one! common-db/ds
                            [(format "UPDATE reports
                            set test_data = jsonb_set_lax(test_data, '( %s }', '%s', true, 'delete_key')
                            WHERE id = ?" "coo" "{}") #uuid"815984ae-21b8-4edb-88e7-0b307cd9c357"]
                            (merge jdbc/unqualified-snake-kebab-opts
                                   {:timeout 5}))
```
However, this creates a problem since now the 2nd field is always a string which for example means even a nill will be treated as a string "null" rather than json null.
So can anyone show the correct way to do multple parameters?

**Comment by seancorfield** [comment]
Questions like this are best answered interactively on either the Clojurians Slack (in the #sql channel) or Clojurians Zulip (again, in the #sql channel). Those are both linked from the README.

That said, the first example is the correct approach, using `?` for the placeholder in the SQL and passing the three parameters inside the vector, after the SQL string. You don't say what happens with the first attempt -- I see `( ? }` in your SQL which isn't going to be valid syntax since `(` doesn't match `}`, but maybe that's just a cut'n'paste error?

I'm closing this out -- but I'll take a look at the docs and see if/where it makes sense to add an example of multiple parameters.

**Comment by Ayush1325** [comment]
Ok, I found the problem though, when using json with prostgresql the way given in the docs, it is also converting vectors of strings to jsonb instead of `text[]`. Thus the following query:
```clojure
(jdbc/execute-one! common-db/ds
                            ["UPDATE reports
                             set test_data = jsonb_set_lax(test_data, ?::text[], ?, true, 'delete_key')
                             WHERE id = ?" ["coo"] {} #uuid"815984ae-21b8-4edb-88e7-0b307cd9c357"]
                             (merge jdbc/unqualified-snake-kebab-opts
                                   {:timeout 5}))
```
Gives the following error:
```
ERROR: function jsonb_set_lax(jsonb, jsonb, jsonb, boolean, unknown) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
```
As the function signature is supposed to be:
`jsonb_set_lax(jsonb, text[], jsonb, boolean, jsonb) `
Also, type casting does not work either:
```
ERROR: cannot cast type jsonb to text[]
  Position: 80
```
It does work if I hardcode the 2nd parameter or create the query using format and basically substitue inside `{}`, But this seems to be a bug.

**Comment by seancorfield** [comment]
Reading the PostgreSQL **Tips & Tricks** section might help you here: https://cljdoc.org/d/seancorfield/next.jdbc/1.1.613/doc/getting-started/tips-tricks#postgresql

I don't use PostgreSQL (except for testing `next.jdbc`) which is why I recommend getting on Slack and asking there since there are PG users who've solved this issue.
