### ISSUE TITLE
Support performant RowBuilders via passing sql-string into `:row-fn`

### ISSUE THREAD

**Issue by ikitommi** [seancorfield/next-jdbc#15]
Currently, the function to map the ResultSet into Clojure Data can't be cached in the user space as the SQL String is not available in the `:row-fn`. This is important perf-wise as cached &/ compiled transforming functions can almost be on par with hand-written ResultSet->Record transformation. Some numbers on the [porsas repo](https://github.com/metosin/porsas#performance).

**Comment by seancorfield** [comment]
There is no `:row-fn` so I assume you mean `:gen-fn`? This is not possible in the general case because the SQL string isn't available if the functions are passed a `PreparedStatement` (which is a common optimization -- and would be the recommended approach for JDBC apps in general).

What I _can_ do is add `:next.jdbc/sql-string` to the `opts` map that is passed into the `:gen-fn` call, from the high-level functions (and it will be `nil` in the `PreparedStatement` case, unless you explicitly call those as `(execute! ps ["the original SQL string passed to build ps"])`

**Comment by seancorfield** [comment]
I'm thinking `:gen-fn` is a terrible name so I'm almost certainly going to rename this in the next release. Probably to `:builder-fn` or just `:builder`. Just a heads up since you're probably the only person trying to use that option right now.
