### ISSUE TITLE
Document how to set driver properties when using a connection pool

### ISSUE THREAD

**Issue by holyjak** [seancorfield/next-jdbc#186]
For next-jdbc and `jdbc.connection/->pool` , it seems that neither the docstring nor the docs mention how to set properties on the underlying Jdbc driver, right? That is understandable since it will differ for each pool but still an example in the docs would be nice. I currently do this for Hikari:

```clojure
(jdbc.connection/->pool com.zaxxer.hikari.HikariConfig
                            {:dbtype "postgres" :host "localhost", :port 5432, :username "ardoq", :password "ardoq"
                             :dataSourceProperties
                             (doto (java.util.Properties.)
                               (.putAll {"socketTimeout" "30"}))})
```

Not sure whether there is a nicer way... ([java.data cannot convert a map to Properties, yet](https://ask.clojure.org/index.php/11163/java-data-should-support-creating-properties-from-a-map))

**Comment by seancorfield** [comment]
I had a look over the c3p0 docs and there doesn't appear to be an equivalent to this -- everything is just a configuration item for c3p0 itself and it does whatever is appropriate, as far as I can tell (and its source code is pretty impenetrable since a bunch of it is auto-generated from XML templates -- eek!).

I'll probably add the `Properties` stuff to `java.data` first and then just document how to use that in the HikariCP-specific docs in `next.jdbc` (and cut new releases).

It'll be a while before I get my next decent OSS window.

**Comment by seancorfield** [comment]
In 1.2.737

**Comment by seancorfield** [comment]
Note: this does not actually work -- it needs to be `com.zaxxer.hikari.HikariDataSource` (instead of `HikariConfig`). Someone just tripped over this in the docs so I'm fixing it.
