### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by vemv** [seancorfield/next-jdbc#217]
Hi,

did you consider naming this repo `next.jdbc` ? GH allows dots.

A couple times I've mistakenly tried to reach for a `next.jdbc` url or local clone.

Cheers - V

**Comment by seancorfield** [comment]
I did consider it -- and I don't remember why I went with `next-jdbc` instead of `next.jdbc` now, especially since all the Contrib library repos have dotted names. It catches me off guard too when I try to type `seancorfield/next.jdbc`. I guess I could rename it and all the links would still work and redirect to the new name but at this point I'm not sure whether it's really worth it...

**Comment by vemv** [comment]
No issue, thanks!
