### ISSUE TITLE
Equivalent of with-db-metadata

### ISSUE THREAD

**Issue by tamizhvendan** [seancorfield/next-jdbc#26]
Thanks, @seancorfield for improving "java.jdbc". 

In this revamped version what is the equivalent of clojure/java.jdbc's [with-db-metadata](https://github.com/clojure/java.jdbc/blob/master/src/main/clojure/clojure/java/jdbc.clj#L871)?

**Comment by seancorfield** [comment]
The metadata facilities in `clojure.java.jdbc` are a very thin layer over Java interop calls to `.getMetaData` and things like `.getTables`. I don't think they offered much value and since `next.jdbc` is based around the Java data types instead of hiding them, interop is even easier.

I'll find some time to whip up an example of metadata operations with `next.jdbc` and add it to this ticket next week -- and I'll add it to the documentation.

**Comment by tamizhvendan** [comment]
Thanks @seancorfield

**Comment by seancorfield** [comment]
I haven't forgotten this -- just had a very busy week. Will try to put together an example this weekend and write it up!

**Comment by seancorfield** [comment]
To support this, I need to expose a function that turns `ResultSet`s into datafiable result sets (vectors of hash maps), but then it becomes this:
```clojure
(with-open [con (jdbc/get-connection ds opts)]
  (-> (.getMetaData con)
      (.getTables nil nil nil (into-array ["TABLE" "VIEW"]))
      (rs/datafiable-result-set ds opts)))]
```
The `rs/datafiable-result-set` function is new.

**Comment by seancorfield** [comment]
This new function will be in release 1.0.0 shortly. You can test it out now via `deps.edn` as a git dep if you want.

**Comment by tamizhvendan** [comment]
Thanks @seancorfield
