### ISSUE TITLE
consider making `plan` results printable

### ISSUE THREAD

**Issue by carocad** [seancorfield/next-jdbc#31]
**Is your feature request related to a problem? Please describe.**
Yes, While on a REPL I was expecting `jdbc/plan` to return printable object, instead I got Java References printes out
```clj
#object[next.jdbc.result_set$eval2218$fn$reify__2220 0x4fa3cd05 "next.jdbc.result_set$eval2218$fn$reify__2220@4fa3cd05"]
```

**Describe the solution you'd like**
I would expect the result of `plan` to print the same as that of `execute!`

**Additional context**
The same problem seems to happen if I use `plan` without `map`. For example
```clj
(with-open [conn (jdbc/get-connection graph-uri)]
  (into [] (take 3) (jdbc/plan conn ["select * from way_node"])))
=>
[#object[next.jdbc.result_set$mapify_result_set$reify__2208
         0x1fd4927
         "next.jdbc.result_set$mapify_result_set$reify__2208@1fd4927"]
 #object[next.jdbc.result_set$mapify_result_set$reify__2208
         0x1fd4927
         "next.jdbc.result_set$mapify_result_set$reify__2208@1fd4927"]
 #object[next.jdbc.result_set$mapify_result_set$reify__2208
         0x1fd4927
         "next.jdbc.result_set$mapify_result_set$reify__2208@1fd4927"]]
```

**Comment by seancorfield** [comment]
Both of these uses are incorrect -- the result of `plan` is an `IReduceInit` instance which has no possible default behavior for printing; the result of `into`/`take` is a bit more subtle: it's a map-like object that you should only interact with directly inside a reduction and it has no usable value outside that, because it wraps a *mutable `ResultSet` object*.

I'll have a think about whether I can add something to produce string outputs that are more informative to at least explain that `plan` is being used incorrectly...

**Comment by seancorfield** [comment]
Probably the best I can do is make them print stuff like this when used incorrectly:
```
#object[next.jdbc.result_set$eval1692$fn$reify__1694 0x5ba90d8a The result of `plan` must be reduced!]

[#object[next.jdbc.result_set$mapify_result_set$reify__1669 0x309dcdf3 The rows from `plan` must be mapped over!] ...
```
I'm not sure what the repercussions would be of adding `toString` to the two `reify` calls like this, however, so that needs more research.

**Comment by seancorfield** [comment]
This is what you'll get in 1.0.0 when that is released (soon):
```clojure
user=> (require '[next.jdbc :as jdbc])
nil
user=> (require '[next.jdbc.result-set :as rs])
nil
user=> (jdbc/get-datasource {:dbtype "h2:mem" :dbname "stuff"})
#object[next.jdbc.connection$url_PLUS_etc$reify__397 0x5486887b "jdbc:h2:mem:stuff;DB_CLOSE_DELAY=-1"]
user=> (def ds *1)
#'user/ds
user=> (jdbc/plan ds ["select 42 as answer"])
#object[next.jdbc.result_set$eval854$fn$reify__856 0x783ec989 "`IReduceInit` from `plan` -- missing reduction?"]
user=> (into [] (jdbc/plan ds ["select 42 as answer"]))
[#object[next.jdbc.result_set$mapify_result_set$reify__831 0x37c5fc56 "{row} from `plan` -- missing `map` or `reduce`?"]]
user=> (into [] (take 3) (jdbc/plan ds ["select 42 as answer"]))
[#object[next.jdbc.result_set$mapify_result_set$reify__831 0x3241713e "{row} from `plan` -- missing `map` or `reduce`?"]]
user=> (into [] (map #(rs/datafiable-row % ds {})) (jdbc/plan ds ["select 42 as answer"]))
[{:ANSWER 42}]
user=> 
```

**Comment by carocad** [comment]
@seancorfield maybe I am interpreting your intention on `plan` wrong but I thought of it as something similar to `eduction` which returns a reducible collection.

The `Eduction` type does have a printable implementation to enable interactive use in the REPL; see [link](https://github.com/clojure/clojure/blob/master/src/clj/clojure/core.clj#L7704)

Are you interested in having `plan` do something like this? or did I misundertood the intention of `plan`.

I would be willing to give this a try if you are interested on it.

Hope it helps

**Comment by seancorfield** [comment]
An `eduction` has all the information it needs to completely render a result -- a collection and the transforms to apply. It is _iterable_. What it prints is the iterable version, not the `IReduceInit` version -- which it *cannot* print because it does not have the `f` or `init` values needed for a reduction. In addition, printing an `eduction` doesn't prevent you from reusing it in another context and reducing it, because it starts with all the information it needs and can run the transforms multiple times.

The result of `plan` is not sufficient to determine what the result is: it is _only_ reducible, not iterable.
