### ISSUE TITLE
sql/find-by-keys throws error on empty key-map

### ISSUE THREAD

**Issue by carocad** [seancorfield/next-jdbc#33]
**Describe the bug**
`(next.jdbc.sql/find-by-keys conn "name" {})` throws an error due to `key-map` being empty.

**To Reproduce**
1. setup a sqlite in memory database
2. create and populate a table with fake information
3. try to fetch all data in the table by using `(next.jdbc.sql/find-by-keys conn "name" {})`
4. an error in thrown due to malformed sql statement

**Expected behavior**
All rows of the table are returned since the `where` clause should be empty

**Stacktraces**
```
Syntax error (SQLiteException) compiling at (osm.clj:42:1).
[SQLITE_ERROR] SQL error or missing database (near " ": syntax error)
```

Hope it helps

**Comment by seancorfield** [comment]
`clojure.java.jdbc` fails in a similar manner because it also assumes the example keys hash map will be non-empty and it always adds the `WHERE` clause. So `next.jdbc` matches that behavior.

I can understand why you might want an empty `key-map` to match all rows but consider that `delete` and `update!` also take a `key-map` and I think most people would *not* want an accidentally empty hash map to silently let them delete every row in a table or update every row. That's a poor default to have.

In `clojure.java.jdbc`, those operations could only accept `["sql condition" param...]` but in `next.jdbc` they accept both and so does `find-by-keys` to improve consistency.

I can understand the desire for the "match all rows" behavior as a default for queries where you're building the map dynamically but I don't want that inconsistency with `delete!` and `update!` for which that behavior would be dangerous.

I'm not going to close this out just yet but I'm deeply against making an empty map behave one way for `find-by-keys` and differently for the more dangerous operations. I might update the (optional) specs so an empty map is trapped as illegal there -- so you can optionally get better error messages earlier in development.

**Comment by carocad** [comment]
> That's a poor default to have

absolutedly, but this is arguably `SQL` default so it shouldnt come as a surprise to anyone using a thin wrapper library.

Please dont get me wrong, I understand your position regarding the consistency of the friendly sql functions and the safety considerations around it. However, the message above is baffling since it is "not directly" the users fault but a decision of the library.

If you decide against accepting an empty map, could we at least improve the error message ?

**Comment by seancorfield** [comment]
That's why I said I might update the specs. Adding logic to all calls for a bad argument slows everyone down. The specs were added as an option for folks who want better/earlier error messages.

**Comment by seancorfield** [comment]
I've updated the spec. If you require and call `(next.jdbc.specs/instrument)`, you'll get a message like this:
```
Call to #'next.jdbc.sql/find-by-keys did not conform to spec.
{:clojure.spec.alpha/problems ({:path [:key-map :example], :pred (clojure.core/<= 1 (clojure.core/count %) Integer/MAX_VALUE), :val {}, :via [:next.jdbc.specs/example-map], :in [2]}
```
