### ISSUE TITLE
Question - casting to uuid

### ISSUE THREAD

**Issue by jacekschae** [seancorfield/next-jdbc#72]
When working with `jdbc.next` I can run following query and cast my id to `uuid` — otherwise it doesn’t work, when using `uuid`s
```clojure
(sql/query db 
    ["select project_id, name, description
      from tasks
      where project_id = ?::uuid" project-id])
```
is it possible to cast in `find-by-keys`?
```clojure
(sql/find-by-keys db :tasks {:project_id project-id})
```

**Comment by seancorfield** [comment]
No. The `next.jdbc.sql` namespace is, by design, very simple and intended purely to ease migration from `clojure.java.jdbc`.

That said, I would expect that if you passed something that the JDBC driver recognized as being directly coercible to the DB-specific UUID data type, it should "Just. Work." but I've no idea what that would need to be.

Another possible avenue is to look at extending `SettableParameter` to perform the coercion automatically.
