### ISSUE TITLE
PostgreSQL: insert! fails for java.util.Date into timestamp column

### ISSUE THREAD

**Issue by valerauko** [seancorfield/next-jdbc#73]
**Is your feature request related to a problem? Please describe.**
Date/time types like java.util.Date and java.time classes (Instant, LocalDateTime) need boilerplate code to be handled correctly by next.jdbc. Date/time types are present in most if not all SQL databases so I'd expect to be able to easily bind them.

**Describe the solution you'd like**
`(extend-protocol SettableParameter` for common date/time types

**Describe alternatives you've considered**
Have every application that uses next.jdbc extend SettableParameter themselves.

**Comment by seancorfield** [comment]
JDBC drivers already handle `java.util.Date` automatically.

Different databases have different SQL types for representing dates/times, with and without timezones, so there is no "one size fits all" that `next.jdbc` could "enforce" for all programs.

`next.jdbc` gives example extensions for some Java Time types https://cljdoc.org/d/seancorfield/next.jdbc/CURRENT/doc/getting-started/prepared-statements#prepared-statement-parameters but those might not be suitable for all users, which is why they are not baked into the library.

**Comment by taurauko** [comment]
>JDBC drivers already handle java.util.Date automatically.

I might be doing things wrong, but `next.jdbc` throws an exception at me if I try to insert a `java.util.Date`.

```
IllegalArgumentException No matching clause: Can't infer the SQL type to use for an instance of java.util.Date. Use setObject() with an explicit Types value to specify the type to use.
```

I'm not saying that `next.jdbc` should "enforce" some kind of mapping, but providing sensible (and in most usecases working) defaults or options to handle this without having to juggle Java type conversions in boilerplate app code would be nice.

**Comment by valerauko** [comment]
>JDBC drivers already handle java.util.Date automatically.

I might be doing things wrong, but `next.jdbc` throws an exception at me if I try to insert a `java.util.Date`.

```
IllegalArgumentException No matching clause: Can't infer the SQL type to use for an instance of java.util.Date. Use setObject() with an explicit Types value to specify the type to use.
```

I'm not saying that `next.jdbc` should "enforce" some kind of mapping, but providing sensible (and in most usecases working) defaults or options to handle this without having to juggle Java type conversions in boilerplate app code would be nice.

**Comment by seancorfield** [comment]
@valerauko I've never seen that error. Can you share your insert code and the schema of your table so I can try to repro? (or better still, jump on Clojurians Slack in the #sql channel and we can chat in real time)

Having maintained `clojure.java.jdbc` for eight years, I can assure you that `next.jdbc` should **not** attempt to provide a default translation for Java Time types because databases vary so much in the date/time types they support -- and doing so would interfere with users' ability to customize that to suit their own applications. I _could_ potentially offer _optional_ namespaces that provide example mappings but they could not be the default.

**Comment by seancorfield** [comment]
I posted this on Slack but this StackOverflow post seems close to what you're seeing https://stackoverflow.com/questions/25536969/spring-jdbc-postgres-sql-java-8-conversion-from-to-localdate (which suggests Java Time, not `java.util.Date`, and an outdated PostgreSQL JDBC driver?).

**Comment by seancorfield** [comment]
I can repro this (now I have all the details, from Slack -- thank you!) with Embedded PG. That is a _weird_ error! I will investigate...
