### ISSUE TITLE
Reified ResultSets throw when used with clojure.core/reductions

### ISSUE THREAD

**Issue by jconti** [seancorfield/next-jdbc#84]
```clojure
(count (reduce (fn [sq row] (conj sq row)) [] (jdbc/plan db [sql])))
==> <a number>
```

But:

```clojure
(count (reductions (fn [_ row] row)) [] (jdbc/plan db [sql])))
==> Execution error (IllegalArgumentException) at ...
Don't know how to create ISeq from: next.jdbc.result_set$eval24569$fn$reify__24571
```

I found this [interesting discussion](https://groups.google.com/d/topic/clojure-dev/SNGLEJ4POnw/discussion).  Based on this and other experiments I wonder if:

- `ISeq` should not be implemented on result sets?
- `IReduce` would be useful too, so the extra collection argument to reductions is not needed?

I am trying to stream a result set to a socket (serializing to JSON) as I go.  My reductions perform side effects.  Is there another way I should be doing that?  (maybe `nav`?).

It seems like a a lazy sequence would be a fine way to do side-effecting result set processing with `doseq` or lazy sequence processing (using `with-open` I imagine).

I am using:
`[seancorfield/next.jdbc "1.0.12"]`
`[org.postgresql/postgresql "42.2.7"]`

 - OS: MacOS 10.14.6
 - Java Version: Java 13.0.1 OpenJDK 64-Bit Server
 - Clojure Version: 1.10.1
 - Database: Postgres 10.11
 - Driver Library Version: [org.postgresql/postgresql "42.2.7"]

**Comment by seancorfield** [comment]
My decision to only implement `IReduceInit` in `next.jdbc` and not `IReduce`, like `clojure.java.jdbc`, is deliberate and based on feedback about the non-`init` version being confusing and error-prone since there is no generally useful `init` value that makes sense for an arbitrary `reduce` of a `ResultSet`.

As you saw in the linked discussion, although the `reduce` docstring is crystal clear about the behavior, the fact that the reducing function may be called with zero or two arguments, and the first element of the `coll` may be used as the `init`, in various situations make that very awkward since it assumes there is a sensible default reduction possible on a `ResultSet` in isolation. The whole point of `plan` is that you want to perform a reduction _without realizing the rows as hash maps_ for performance reasons. What you get back from `plan` is reducible -- it is specifically _not_ a sequence (nor `Seqable`). This also allows you to reduce a very large result set that would not otherwise all fit in memory if it was fully realized.

As soon as you try to treat the result of `plan` as a sequence, instead of a reducible, you're forcing realization of rows as full-blown Clojure hash maps, and forcing realization of the whole result set -- because you cannot have a lazy sequence here: the eager reduction allows for resource management in the reducible because the `ResultSet` is mutable and consumption of it is side-effecting.

I don't understand why you think you need `reductions` here -- `reductions` operates on a sequence, explicitly, not a reducible. You could use `reduce` here and have it serialize each row onto the socket as JSON -- passing the socket as the `init` value and returning that value from your reducing function:

```clj
(reduce (fn [sock row] 
           (write-json-to-socket sock row) 
           sock) 
        my-socket 
        (jdbc/plan db [sql]))
```

Depending on exactly what `write-json-to-socket` does, you may need to explicitly call `rs/datafiable-row` on `row` (but I suspect it will "do the right thing" automatically).
