### ISSUE TITLE
This ResultSet is closed, when try to aggregate rows using transduce

### ISSUE THREAD

**Issue by zerg000000** [seancorfield/next-jdbc#99]
**Describe the bug**

the last result will be 
```
{row} from `plan` -- missing `map` or `reduce`?`
``` 
when I try to transduce the `plan`

**To Reproduce**

```clojure
(with-open
    [conn (jdbc/get-connection ds)]
    (transduce (comp (partition-all 10)
                     (map prn))
               conj
               (jdbc/plan conn query))
[...]
[...]
[{row} from `plan` -- missing `map` or `reduce`? {row} from `plan` -- missing `map` or `reduce`? {row} from `plan` -- missing `map` or `reduce`? {row} from `plan` -- missing `map` or `reduce`? {row} from `plan` -- missing `map` or `reduce`? {row} from `plan` -- missing `map` or `reduce`? {row} from `plan` -- missing `map` or `reduce`?]
```

**Expected behavior**

all rows should be printed in the example

**project.clj/deps.edn**

```clojure
{:paths ["src" "resources"]
 :deps {org.postgresql/postgresql {:mvn/version "42.2.9"}
        seancorfield/next.jdbc {:mvn/version "1.0.395"}
        metosin/jsonista {:mvn/version "RELEASE"}}}
```

**Environment (please complete the following information):**
 - OS: Mac OSX 10.14.6
 - Java Version: OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)
 - Clojure Version: 1.10.1
 - Database: mdillon/postgis:9.5
 - Driver Library Version: org.postgresql/postgresql {:mvn/version "42.2.9"}

**Comment by seancorfield** [comment]
The abstraction behind `plan` requires that you process the _rows_, not just the result set, because there is a _mutable_ `ResultSet` object behind it.

If you look at the output from your code, even aside from the `{row} from plan` values being printed, you should see that each partition being printed repeats the first row of each group ten times.

You need a step in your reduction that realizes some data structure from each row, either by calling `next.jdbc.result-set/datafiable-row` on it, or selecting a subset of keys, or by processing individual columns.

An example of realizing the whole of each row would be:
```clojure
(require '[next.jdbc :as jdbc] '[next.jdbc.result-set :as rs])
(with-open [conn (jdbc/get-connection db-spec)] 
  (transduce (comp (map #(rs/datafiable-row % conn {})) 
                   (partition-all 10) 
                   (map prn)) 
             conj 
             (jdbc/plan conn query)))
```
The key here is that you must do _something_ to lift data out of the abstract row in your reduction.

**Comment by seancorfield** [comment]
Let me know if you have suggestions for making this clearer in the docs. I've already updated https://github.com/seancorfield/next-jdbc/blob/master/doc/getting-started.md#plan--reducing-result-sets substantially based on feedback on Slack but this expanded section hasn't made it to cljdoc.org yet (it will be in the next release).
